function [p,f,t] = spectrumAnalyse(audiodata, Fs, lowestFreq, timeResolution)
    [p,f,t] = pspectrum(audiodata,Fs,'spectrogram',...
    'TimeResolution', timeResolution,...
    'Leakage',1,'OverlapPercent',85,'MinThreshold',-60,...
    'FrequencyLimits',[lowestFreq, Fs/4],'Reassign',true);
end