function [p,f,t] = spectrumAnalyse(audiodata, Fs, lowestFreq, timeResolution,freqResolution, resolutionMode)
    if(strcmp(resolutionMode,'time'))
        [p,f,t] = pspectrum(audiodata,Fs,'spectrogram',...
        'TimeResolution', timeResolution,...
        'Leakage',1,'OverlapPercent',85,'MinThreshold',-60,...
        'FrequencyLimits',[lowestFreq, Fs/4],'Reassign',true);
    end
    if(strcmp(resolutionMode,'freq'))
        [p,f,t] = pspectrum(audiodata,Fs,'spectrogram',...
        'FrequencyResolution', freqResolution,...
        'Leakage',1,'OverlapPercent',85,'MinThreshold',-60,...
        'FrequencyLimits',[lowestFreq, Fs/4],'Reassign',true);
    end 
end