function [p,f,t] = spectrumAnalyse(audiodata, Fs)
    [p,f,t]=pspectrum(audiodata,Fs,'spectrogram','FrequencyResolution',1,...
    'Leakage',1,'OverlapPercent',85,'MinThreshold',-65,...
    'FrequencyLimits',[60, Fs/4],'Reassign',true);
end