function spectrumTest(audiodata, Fs, lowestFreq, timeResolution, freqResolution, resolutionMode, freqScale, ampScale)
    if(strcmp(resolutionMode,'time'))
        pspectrum(audiodata,Fs,'spectrogram',...
        'TimeResolution', timeResolution,...
        'Leakage',1,'OverlapPercent',85,'MinThreshold',-60,...
        'FrequencyLimits',[lowestFreq, Fs/4],'Reassign',true);
        setAx(freqScale,ampScale);
    end
    if(strcmp(resolutionMode,'freq'))
         pspectrum(audiodata,Fs,'spectrogram',...
        'FrequencyResolution', freqResolution,...
        'Leakage',1,'OverlapPercent',85,'MinThreshold',-60,...
        'FrequencyLimits',[lowestFreq, Fs/4],'Reassign',true);
        setAx(freqScale,ampScale);
    end 
end